### ISSUE TITLE
clr memory instruction has an extra cycle.

### ISSUE THREAD

**Issue by JNSpears** [raybellis/usim#10]
Ray I found this while working on some new features in usim.
--James.
 
void mc6809::clr()
{
	insn = "CLR";
	Word	addr = fetch_effective_address();
	Byte	m = read(addr);  // <<<<------ causes a read that should not be there according to my understanding.
	help_clr(m);
	write(addr, m);
}
```

**Comment by raybellis** [comment]
Sorry for the delay - GitHub's email notifications haven't been reaching me!

This extra cycle appears on sheet 5 of figure 18.  I think this is because this instruction is grouped among the read-modify-write operations, even though it doesn't actually care what the current contents of `addr` are.

**Comment by raybellis** [comment]
p.s. I'd love to hear about the features you're planning!

**Comment by JNSpears** [comment]
Ray, I worked for Intel for 30+ years, starting with I2Ice an VlsIce
products for x86 and embedded processors. So it was only logical to build a
debugger that plugs into USim. execution breaks, data r/w breaks, trace
etc. the trace system showed the read cycle on the clr instructions does
the real cpu do that? Currently my 6809 system is down. But I have been
developing extensions to the old Percom MPX9 os it ran, wanted to include
multitasking hence the timer question.

**Comment by raybellis** [comment]
I can't tell you if the real CPU does perform that extra read cycle, but the datasheet says it does :)

(I first started writing USim to support an MC6809 SBC I had planned.  The code still lives, but the SBC never happened, so I also have no running 6809 system).

In the ALFASoniQ project (not yet public) we do also have a subclass of mc6809 that adds break points and instruction tracing, but not some of the more extensive debugger features that you've added.    I've been mulling over whether I could add those as part of the tilde-escape sequence that I recently added to the main code via the `Terminal` class.

**Comment by raybellis** [comment]
If I'm reading the MAME code correctly that cycle appears there, too:
https://github.com/mamedev/mame/blob/36f5b6e3be7a2b4e7f9539d1bc9ddc683f7b95f2/src/devices/cpu/m6809/base6x09.lst#L182C6-L182C6

**Comment by JNSpears** [comment]
Ray, I have been revising the debugger I built on top of usim. there are some changes that were necessary to make in the usim code to do everything I wanted. I'm planning on a bit more cleanup, and then do a pull request. I would like to know it you would like to just have the usim changes, or the entire debugger, or would you like to have me keep the debugger in a separate repo? if so I'll back out some of the changes I added to usim (make builds libraries that are used for building usim and usimd). also if you are willing could you share your 6522 device?
