### ISSUE TITLE
License

### ISSUE THREAD

**Issue by trcwm** [raybellis/usim#3]
Hi Ray,

Does this project have a software license?

Regards,
Niels.

**Comment by raybellis** [comment]
It didn't have a specific one before, but it does now (the MPL-2.0 License).

**Comment by trcwm** [comment]
Thank you! :+1:

**Comment by raybellis** [comment]
If you do end up using it for something, please do let me know! :)

**Comment by trcwm** [comment]
It's [here](https://github.com/trcwm/HD6309-Sim) and [here](https://namoseley.wordpress.com/2019/10/05/retrochallenge-2019-10-1/).
