### ISSUE TITLE
No Reset Vector in tests/tbasic.s

### ISSUE THREAD

**Issue by rmerkel** [raybellis/usim#8]
Currently, the END directive in tbasic.s is before the reset vector,

`;*****************************
;*****************************
	END	BASIC

	ORG	$FFFE
	FDB	BASIC`

The the resultant HEX/S19 file lacks a resetvector, and the simulator defaults to zero. When run, usim starts running at address zero!

"END BASIC" should be moved after "FDB BASIC"

**Comment by raybellis** [comment]
Thanks for spotting that - a simpler fix seems to be to just remove the `END BASIC` line altogether (resolved in 30ef8c7).
