### ISSUE TITLE
Configuring usim for multiple rom regions

### ISSUE THREAD

**Issue by JNSpears** [raybellis/usim#9]
When trying to setup usim to emulate a Percom SBC/9 single board computer I'm having the following problem. There are two roms on the card, the first (the monitor) checks to see if the second (the monitor extensions) is present and uses it to add new functionality to the monitor.

The problem is the read of the second rom gets data that is in the first. This may be I'm not setting up the images correctly (my STL is limited and very rusty) but it all looks good to me.

`james@:~/Documents/6809/github/Percom/PsyMon/bug$ make -B

lwasm -lromfc00.lst  -fihex -oromfc00.hex romfc00.asm

lwasm -lromf800.lst  -fihex -oromf800.hex romf800.asm

james@:~/Documents/6809/github/Percom/PsyMon/bug$ 
`

`james@:~/Documents/6809/github/Percom/PsyMon/bug$ '/home/james/workspace/6809/tools/usim/usim' romfc00.hex romf800.hex 
PC:FC00 CC:-F-I---- S:0000 U:7F9C A:00 B:00 X:0000 Y:0000 DP:00

/ FC00: [ 5] LDA     **$F800**

PC:FC03 CC:-F-IN--- S:0000 U:7F9C A:**B6** B:00 X:0000 Y:0000 DP:00

/ FC03: [ 2] CMPA    #$7E

PC:FC05 CC:-F-I--V- S:0000 U:7F9C A:B6 B:00 X:0000 Y:0000 DP:00

/ FC05: [ 4] JMP     $FC00

PC:FC00 CC:-F-I--V- S:0000 U:7F9C A:B6 B:00 X:0000 Y:0000 DP:00

/ FC00: [ 5] LDA     $F800

PC:FC03 CC:-F-IN--- S:0000 U:7F9C A:B6 B:00 X:0000 Y:0000 DP:00

/ FC03: [ 2] CMPA    #$7E

PC:FC05 CC:-F-I--V- S:0000 U:7F9C A:B6 B:00 X:0000 Y:0000 DP:00

/ FC05: [ 4] JMP     $FC00

PC:FC00 CC:-F-I--V- S:0000 U:7F9C A:B6 B:00 X:0000 Y:0000 DP:00

/ FC00: [ 5] LDA     $F800

PC:FC03 CC:-F-IN--- S:0000 U:7F9C A:B6 B:00 X:0000 Y:0000 DP:00

/ FC03: [ 2] CMPA    #$7E

PC:FC05 CC:-F-I--V- S:0000 U:7F9C A:B6 B:00 X:0000 Y:0000 DP:00

/ FC05: [ 4] JMP     $FC00

PC:FC00 CC:-F-I--V- S:0000 U:7F9C A:B6 B:00 X:0000 Y:0000 DP:00

/ FC00: [ 5] LDA     $F800

james@:~/Documents/6809/github/Percom/PsyMon/bug$ 
`

files were renamed because github would not let me upload them...

[mainPercom.cpp.txt](https://github.com/raybellis/usim/files/8301728/mainPercom.cpp.txt)
[Makefile.txt](https://github.com/raybellis/usim/files/8301732/Makefile.txt)
[romf800.asm.txt](https://github.com/raybellis/usim/files/8301736/romf800.asm.txt)
[romfc00.asm.txt](https://github.com/raybellis/usim/files/8301737/romfc00.asm.txt)
.

I had the monitor, extensions, MPX/9, forth etc all working on version 0.91 so I suspect it is something to do with my setup of the ROMs.

**Comment by raybellis** [comment]
Both of your ASM files are starting at `ORG ROM1`, i.e. `$FC00`.   The Intel Hex loader uses the actual addresses saved in the assembled files and should ignore any data that falls outside the defined memory range for that ROM object.  I suggest you fix that first, and then see if the problem persists.

**Comment by raybellis** [comment]
You're also attaching the `SBC9_BootRom` object twice - the second call to `cpu.attach` needs to have `SBC_ExtRom` for the first parameter.

**Comment by JNSpears** [comment]
The org statement was fixed previously I neglected to update the attached files. The attach call was the original culprit, thanks!
Everything is working and ready to move forward again.
Thanks,
--James.
